
# Generated by Django 5.1.6 on 2025-02-27 10:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_category_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',

            field=models.FloatField(default=1),

            field=models.FloatField(default=100000),

            preserve_default=False,
        ),
    ]
